export const livrosDisponiveis = [
    { nome: '5 Aneis', capa:'/src/assets/5aneis.jpg'},
    { nome: 'Arte da Guerra' , capa:'/src/assets/artedaguerra.jpg'},
    { nome: 'Biblia', capa:'/src/assets/biblia.jpg'},
    { nome: 'Biblia', capa:'/src/assets/bushido.jpg'},
    { nome: 'Biblia', capa:'/src/assets/corte.jpg'},
    { nome: 'Biblia', capa:'/src/assets/diario.jpg'},
    { nome: 'Biblia', capa:'/src/assets/harry.jpg'},
    { nome: 'Biblia', capa:'/src/assets/mitologia.jpg'},
    { nome: 'Biblia', capa:'/src/assets/narnia.jpg'},
    { nome: 'Biblia', capa:'/src/assets/narnia2.jpg'},
    { nome: 'Biblia', capa:'/src/assets/percy.jpg'},
    { nome: 'Biblia', capa:'/src/assets/sherlock.jpg'},
    { nome: 'Biblia', capa:'/src/assets/tronos.jpg'},
];