function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

export const livrosDisponiveis = shuffleArray([
    { numero: 1, nome: 'Livor dos 5 Aneis', description: 'O livro dos cinco anéis é um guia de estratégias que se tornou uma espécie de bíblia para executivos do mundo contemporâneo. Escrito pelo samurai Musashi no século XV, o livro traz para o leitor de hoje uma sabedoria ancestral, apresentando os princípios básicos que conduzem à vitória, seja no campo de batalha, seja em qualquer forma de competição. Esta é uma obra para se ler e reler, descobrindo a cada leitura significados novos e reveladores.', capa:'/src/assets/5aneis.jpg', leitura: Math.random()},
    { numero: 2, nome: 'Arte da Guerra', description: 'A arte da guerra" é um clássico da literatura mundial por ser o primeiro tratado militar de que se tem noticia. Atribuída ao general chinês Sun Tzu, a obra é uma coletânea de disposições a respeito de táticas de combate e aniquilação dos inimigos. Durante todos esses anos, o livro se manteve no topo dos mais populares entre os apreciadores de guerra, e passou a ser lido também por públicos variados, interessados em aplicar os ensinamentos de Sun Tzu nas relações de trabalho e pessoas interessadas em obter sucesso em diferentes áreas.',  capa:'/src/assets/artedaguerra.jpg', leitura: Math.random()},
    { numero: 3, nome: 'Biblia Infantil', description: 'Os textos religiosos, alguns também considerados sagrados, são de grande importância no momento de compreender e conhecer diferentes crenças. Esses livros fazem parte da cultura da sociedade.',  capa:'/src/assets/biblia.jpg', leitura: Math.random()},
    { numero: 4, nome: 'Bushido', description: 'O livro apresenta um estudo sobre as tradições, usos e costumes dos samurais, uma classe de nobres militares e guerreiros. Obra seminal e única sobre o Japão da era Meiji (1868-1912), foi usada para divulgar a cultura japonesa às nações ocidentais e favorecer as suas relações internacionais.',  capa:'/src/assets/bushido.jpg', leitura: Math.random()},
    { numero: 5, nome: 'Corte de Espinhos e Rosas', description: 'Num mundo dividido uma muralha mágica separa duas espécies. De um lado, os feéricos vivem dentro de suas fronteiras cheias de beleza e mistério; do outro, os humanos possuem apenas medo, desconfiança e dificuldades. Feyre, filha de um casal de mercadores humanos e falidos, se torna caçadora para sustentar a família.',  capa:'/src/assets/corte.jpg', leitura: Math.random()},
    { numero: 6, nome: 'O Diário Perdido', description: 'Você possui em suas mãos o cobiçado diário do autor da série Gravity Falls, um tesouro de 288 páginas coloridas e sem dono, com segredos nunca antes revelados, monstros e mistérios da pacata cidade do Tivô Stan.',  capa:'/src/assets/diario.jpg', leitura: Math.random()},
    { numero: 7, nome: 'Harry Potter', description: 'Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo.No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico.',  capa:'/src/assets/harry.jpg', leitura: Math.random()},
    { numero: 8, nome: 'Mitologia Nórdica', description: 'Quem, além de Neil Gaiman, poderia se tornar cúmplice dos deuses e usar de sua habilidade com as palavras para recontar as histórias dos mitos nórdicos? Fãs e leitores sabem que a mitologia nórdica sempre teve grande influência na obra do autor. Depois de servirem de inspiração para clássicos como Deuses americanos e Sandman, Gaiman agora investiga o universo dos mitos nórdicos.',  capa:'/src/assets/mitologia.jpg', leitura: Math.random()},
    { numero: 9, nome: 'Nárnia', description: 'O Leão, a Feiticeira e o Guarda-roupa  conta a história dos irmãos Pedro, Susana, Edmundo e Lúcia Pevensie. Em meio a brincadeiras na casa de um velho professor, eles descobrem um misterioso guarda-roupa que os leva a Nárnia, um reino mágico que sofre de um inverno sem fim desde que Jadis, a temida Feiticeira Branca, tomou o poder. Mas uma antiga profecia ― que envolve justamente quatro crianças, além de um fantástico leão chamado Aslan ― afirma que há esperança para o reino, contanto que se tenha coragem.',  capa:'/src/assets/narnia.jpg', leitura: Math.random()},
    { numero: 10, nome: 'Nárnia Vol. Único', description: 'Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal. Este livro apresenta as sete crônicas de Nárnia integralmente, num único volume. Os livros são apresentados de acordo com a ordem de preferência do autor, cada capítulo com uma ilustração do artista Pauline Baynes. ´As crônicas de Nárnia´ apresenta aventuras, personagens e fatos que falam aos leitores de todas as idades.',  capa:'/src/assets/narnia2.jpg', leitura: Math.random()},
    { numero: 11, nome: 'Percy Jackson', description: 'Unindo mitologia grega, muita aventura e tramas hilárias, a história de Rick Riordan sobre um adolescente com TDAH que descobre ser filho do deus do mar e precisa navegar entre o mundo humano e o divino se tornou um best-seller e formou uma geração de leitores apaixonados, que até hoje acompanham a saga de Percy e seus amigos. Agora, a Intrínseca relança os cinco livros da série em uma edição com nova arte de capa, muito pedida pelos leitores.',  capa:'/src/assets/percy.jpg', leitura: Math.random()},
    { numero: 12, nome: 'Sherlock Holmes', description: 'Sherlock Holmes é um detetive britânico enigmático e pedante do final do século XIX e início do século XX. Ele utiliza a metodologia científica e a lógica dedutiva para solucionar seus casos e conta com a ajuda de seu fiel amigo e parceiro dr. Watson. Observação, perspicácia e um pouco de intuição são alguns dos instrumentos usados por Sherlock Holmes para desvendar os seis curiosos casos reunidos nesta obra e narrados pelo atento doutor Watson.',  capa:'/src/assets/sherlock.jpg', leitura: Math.random()},
    { numero: 13, nome: 'Guerra dos Tronos', description: 'Nas florestas ao norte de Winterfell, forças sobrenaturais se espalham por trás da Muralha que protege a região. E, nas Cidades Livres, o jovem Rei Dragão exilado na Rebelião de Robert planeja sua vingança e deseja recuperar sua herança de família: o Trono de Ferro de Westeros.',  capa:'/src/assets/tronos.jpg', leitura: Math.random()},
]);
