export const livrosDisponiveis = [
    { nome: '5 Aneis', capa:'/src/assets/5aneis.jpg'},
    { nome: 'Arte da Guerra' , capa:'/src/assets/artedaguerra.jpg'},
    { nome: 'Biblia', capa:'/src/assets/biblia.jpg'},
    { nome: 'Bushido', capa:'/src/assets/bushido.jpg'},
    { nome: 'Corte', capa:'/src/assets/corte.jpg'},
    { nome: 'Diário', capa:'/src/assets/diario.jpg'},
    { nome: 'Harry', capa:'/src/assets/harry.jpg'},
    { nome: 'Mitologia', capa:'/src/assets/mitologia.jpg'},
    { nome: 'Nárnia ', capa:'/src/assets/narnia.jpg'},
    { nome: 'Nárnia', capa:'/src/assets/narnia2.jpg'},
    { nome: 'Percy', capa:'/src/assets/percy.jpg'},
    { nome: 'Sherlock', capa:'/src/assets/sherlock.jpg'},
    { nome: 'Guerra', capa:'/src/assets/tronos.jpg'},
];